// This file tests `meru check report`: grouping results by model set, the
// pass rates of each run, the percentiles, and the Markdown page.

package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestQuantile(t *testing.T) {
	xs := []float64{5, 1, 4, 2, 3}
	tests := []struct {
		q    float64
		want float64
	}{{0.5, 3}, {0.95, 5}, {0.2, 1}, {0, 1}}
	for _, tt := range tests {
		if got := quantile(xs, tt.q); got != tt.want {
			t.Errorf("quantile(%v) = %v, want %v", tt.q, got, tt.want)
		}
	}
	if xs[0] != 5 {
		t.Errorf("quantile sorted its input: %v", xs)
	}
	if got := median(nil); got != 0 {
		t.Errorf("median(nil) = %v, want 0", got)
	}
}

func TestSummarize(t *testing.T) {
	results := []checkResult{
		// Two runs of the qwen set: 2 of 2, then 1 of 2.
		{Run: "r1", ModelSet: "qwen", Model: "qwen:35b", Category: "t0", Pass: true, TTFTMillis: 1000, TTLTMillis: 2000, TPOTMillis: 10, TokensIn: 100, TokensOut: 5},
		{Run: "r1", ModelSet: "qwen", Model: "qwen:35b", Category: "t3", Pass: true, TTFTMillis: 3000, TTLTMillis: 9000, TPOTMillis: 20, TokensIn: 300, TokensOut: 50},
		{Run: "r2", ModelSet: "qwen", Model: "qwen:35b", Category: "t0", Pass: true, TTFTMillis: 1000, TTLTMillis: 2000},
		{Run: "r2", ModelSet: "qwen", Model: "qwen:35b", Category: "t3", Pass: false},
		// One result with no set groups under its model.
		{Run: "r3", Model: "gemma:26b", Category: "t0", Pass: false},
	}
	sets := summarize(results)
	if len(sets) != 2 || sets[0].Name != "qwen" || sets[1].Name != "gemma:26b" {
		t.Fatalf("sets = %+v, want qwen then gemma:26b", sets)
	}
	q := sets[0]
	if q.Runs != 2 || q.Total != 4 || q.Passed != 3 || q.Low != 50 || q.High != 100 {
		t.Errorf("qwen = %d runs, %d/%d passed, runs %v%%–%v%%; want 2 runs, 3/4, 50%%–100%%",
			q.Runs, q.Passed, q.Total, q.Low, q.High)
	}
	if got := q.ByCategory["t3"]; got != [2]int{1, 2} {
		t.Errorf("qwen t3 = %v, want [1 2]", got)
	}
	// The failed turn with no done event stays out of the timings.
	if len(q.TTLT) != 3 || median(q.TTLT) != 2 || median(q.TPOT) != 10 {
		t.Errorf("qwen TTLT %v, TPOT %v; want 3 timings with median 2 s, TPOT median 10 ms", q.TTLT, q.TPOT)
	}

	page := reportMarkdown(sets, categoriesOf(results), time.Date(2026, 9, 27, 0, 0, 0, 0, time.UTC))
	for _, want := range []string{
		"author's private dataset",
		"Generated by `meru check report` on 27 September 2026.",
		"```mermaid\nxychart-beta\n    title \"Questions passed (%)\"\n    x-axis [\"qwen\", \"gemma:26b\"]\n    y-axis 0 --> 100\n    bar [75.0, 0.0]\n```",
		"| qwen | `qwen:35b` | 2 | 4 | 75% | 50% | 100% |",
		"| t3 | 50% (1/2) | — |",
		// The trade-off charts: a coloured point per set, and a key.
		"```mermaid\nquadrantChart\n    title Passed by first token: 0 to 10 s, 0% to 100%\n",
		"    qwen: [0.100, 0.750] color: #1f77b4, radius: 7\n",
		"| 🔵 | qwen | 75% | 1.0 s |",
		// Time charts put the fastest set first: gemma:26b has no timings, so 0 s.
		"title \"Median time to last token (s)\"\n    x-axis [\"gemma:26b\", \"qwen\"]\n    bar [0.0, 2.0]",
	} {
		if !strings.Contains(page, want) {
			t.Errorf("page lacks %q\n%s", want, page)
		}
	}
}

func TestCheckReportCmd(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "r.jsonl")
	line, _ := json.Marshal(checkResult{Run: "r1", ModelSet: "qwen", Category: "t0", Pass: true})
	if err := os.WriteFile(path, append(line, '\n'), 0o600); err != nil {
		t.Fatal(err)
	}
	var out, errOut bytes.Buffer
	if code := run(t.Context(), []string{"check", "report", path}, &out, &errOut); code != exitOK {
		t.Fatalf("exit code = %d, stderr %q", code, errOut.String())
	}
	if !strings.Contains(out.String(), "| qwen |") {
		t.Errorf("stdout = %q, want the qwen row", out.String())
	}
	if code := run(t.Context(), []string{"check", "report"}, &out, &errOut); code != exitError {
		t.Errorf("no files: exit code = %d, want %d", code, exitError)
	}
}
